sudo: false
language: python
dist: xenial
matrix:
    include:
        - python: pypy2.7-6.0
          env: TOXENV=pypy
        - python: pypy3.5-6.0
          env: TOXENV=pypy3
        - python: 2.7
          env: TOXENV=py27
        - python: 2.7
          env: TOXENV=py27_cython
        - python: 3.4
          env: TOXENV=py3.4
        - python: 3.4
          env: TOXENV=py3.4_cython
        - python: 3.5
          env: TOXENV=py3.5
        - python: 3.5
          env: TOXENV=py3.5_cython
        - python: 3.6
          env: TOXENV=py3.6
        - python: 3.6
          env: TOXENV=py3.6_cython
        - python: 3.7
          env: TOXENV=py3.7
        - python: 3.7
          env: TOXENV=py3.7_cython

install: pip install tox codecov
script: tox
after_success:
  - codecov
