sudo: false
language: python
dist: xenial
matrix:
    include:
        - python: 3.7
          env: TOXENV=pep8
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py3.4
        - python: 3.5
          env: TOXENV=py3.5
        - python: 3.6
          env: TOXENV=py3.6
        - python: 3.7
          env: TOXENV=py3.7

install: pip install cython tox
script: tox
